// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlcgen

import (
	"database/sql"
	"time"
)

type IdempotencyKey struct {
	TenantID       string
	Route          string
	IdempotencyKey string
	RequestHash    string
	ResponseStatus sql.NullInt32
	ResponseBody   []byte
	CreatedAt      time.Time
	ExpiresAt      time.Time
}

type Widget struct {
	ID        string
	TenantID  string
	Name      string
	CreatedAt time.Time
}
