// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package sqlcgen

import (
	"context"
	"database/sql"
	"time"
)

const completeIdempotency = `-- name: CompleteIdempotency :exec
UPDATE idempotency_keys
SET response_status = $4, response_body = $5
WHERE tenant_id = $1 AND route = $2 AND idempotency_key = $3
`

type CompleteIdempotencyParams struct {
	TenantID       string
	Route          string
	IdempotencyKey string
	ResponseStatus sql.NullInt32
	ResponseBody   []byte
}

func (q *Queries) CompleteIdempotency(ctx context.Context, arg CompleteIdempotencyParams) error {
	_, err := q.db.ExecContext(ctx, completeIdempotency,
		arg.TenantID,
		arg.Route,
		arg.IdempotencyKey,
		arg.ResponseStatus,
		arg.ResponseBody,
	)
	return err
}

const createWidget = `-- name: CreateWidget :exec

INSERT INTO widgets (id, tenant_id, name, created_at)
VALUES ($1, $2, $3, $4)
`

type CreateWidgetParams struct {
	ID        string
	TenantID  string
	Name      string
	CreatedAt time.Time
}

// queries.sql is the sqlc source of truth for the widgets store. sqlc generates
// the typed Go in internal/db/sqlcgen from these annotated queries against the
// goose migration schema (see sqlc.yaml). Regenerate with: go tool sqlc generate.
//
// Every read and write is scoped by tenant_id so one tenant can never observe
// another's rows: multi-tenancy is enforced in the WHERE clause, not only at the
// transport edge.
func (q *Queries) CreateWidget(ctx context.Context, arg CreateWidgetParams) error {
	_, err := q.db.ExecContext(ctx, createWidget,
		arg.ID,
		arg.TenantID,
		arg.Name,
		arg.CreatedAt,
	)
	return err
}

const getIdempotency = `-- name: GetIdempotency :one
SELECT request_hash, response_status, response_body
FROM idempotency_keys
WHERE tenant_id = $1 AND route = $2 AND idempotency_key = $3 AND expires_at > $4
`

type GetIdempotencyParams struct {
	TenantID       string
	Route          string
	IdempotencyKey string
	ExpiresAt      time.Time
}

type GetIdempotencyRow struct {
	RequestHash    string
	ResponseStatus sql.NullInt32
	ResponseBody   []byte
}

func (q *Queries) GetIdempotency(ctx context.Context, arg GetIdempotencyParams) (GetIdempotencyRow, error) {
	row := q.db.QueryRowContext(ctx, getIdempotency,
		arg.TenantID,
		arg.Route,
		arg.IdempotencyKey,
		arg.ExpiresAt,
	)
	var i GetIdempotencyRow
	err := row.Scan(&i.RequestHash, &i.ResponseStatus, &i.ResponseBody)
	return i, err
}

const getWidget = `-- name: GetWidget :one
SELECT id, tenant_id, name, created_at
FROM widgets
WHERE tenant_id = $1 AND id = $2
`

type GetWidgetParams struct {
	TenantID string
	ID       string
}

func (q *Queries) GetWidget(ctx context.Context, arg GetWidgetParams) (Widget, error) {
	row := q.db.QueryRowContext(ctx, getWidget, arg.TenantID, arg.ID)
	var i Widget
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Name,
		&i.CreatedAt,
	)
	return i, err
}

const insertIdempotency = `-- name: InsertIdempotency :execrows

INSERT INTO idempotency_keys (tenant_id, route, idempotency_key, request_hash, created_at, expires_at)
VALUES ($1, $2, $3, $4, $5, $6)
ON CONFLICT (tenant_id, route, idempotency_key) DO UPDATE
    SET request_hash = EXCLUDED.request_hash,
        response_status = NULL,
        response_body = NULL,
        created_at = EXCLUDED.created_at,
        expires_at = EXCLUDED.expires_at
    WHERE idempotency_keys.expires_at <= EXCLUDED.created_at
`

type InsertIdempotencyParams struct {
	TenantID       string
	Route          string
	IdempotencyKey string
	RequestHash    string
	CreatedAt      time.Time
	ExpiresAt      time.Time
}

// Idempotency-Key store (recipes/add-idempotent-write.md). Keyed by
// (tenant_id, route, idempotency_key) so a client key is scoped per tenant and
// endpoint. A row is reserved (response_status NULL) on first use and updated
// with the response when the write completes, so a duplicate replays it. The
// TTL is enforced with expires_at.
// Reserve the key on first use; if a row already exists it is reclaimed ONLY
// when expired (expires_at <= now). The affected-row count tells the caller
// whether it won the lease (1) or a live row already exists (0); on 0 the caller
// reads the existing row to decide replay vs. in-flight vs. mismatch. This is the
// atomic compare-and-set that closes the concurrent-duplicate race.
func (q *Queries) InsertIdempotency(ctx context.Context, arg InsertIdempotencyParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, insertIdempotency,
		arg.TenantID,
		arg.Route,
		arg.IdempotencyKey,
		arg.RequestHash,
		arg.CreatedAt,
		arg.ExpiresAt,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const listWidgets = `-- name: ListWidgets :many
SELECT id, tenant_id, name, created_at
FROM widgets
WHERE
    tenant_id = $1
    AND (
        $2::boolean
        OR (created_at, id) > ($3::timestamptz, $4::text)
    )
ORDER BY created_at, id
LIMIT $5
`

type ListWidgetsParams struct {
	TenantID        string
	FromStart       bool
	CursorCreatedAt time.Time
	CursorID        string
	PageLimit       int32
}

// Keyset pagination over the stable (created_at, id) order WITHIN a tenant. The
// tenant_id predicate scopes every page; when @from_start is true the
// row-comparison guard is bypassed and the scan starts at the tenant's first
// row; otherwise it resumes strictly after the cursor (@cursor_created_at,
// @cursor_id) using a tuple comparison so id breaks created_at ties and pages
// neither overlap nor skip rows. The caller asks for one more than the page size
// to detect whether another page exists.
func (q *Queries) ListWidgets(ctx context.Context, arg ListWidgetsParams) ([]Widget, error) {
	rows, err := q.db.QueryContext(ctx, listWidgets,
		arg.TenantID,
		arg.FromStart,
		arg.CursorCreatedAt,
		arg.CursorID,
		arg.PageLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Widget{}
	for rows.Next() {
		var i Widget
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.Name,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const releaseIdempotency = `-- name: ReleaseIdempotency :exec
DELETE FROM idempotency_keys
WHERE tenant_id = $1 AND route = $2 AND idempotency_key = $3 AND response_status IS NULL
`

type ReleaseIdempotencyParams struct {
	TenantID       string
	Route          string
	IdempotencyKey string
}

func (q *Queries) ReleaseIdempotency(ctx context.Context, arg ReleaseIdempotencyParams) error {
	_, err := q.db.ExecContext(ctx, releaseIdempotency, arg.TenantID, arg.Route, arg.IdempotencyKey)
	return err
}
