// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlcgen

import (
	"context"
)

type Querier interface {
	CompleteIdempotency(ctx context.Context, arg CompleteIdempotencyParams) error
	// queries.sql is the sqlc source of truth for the widgets store. sqlc generates
	// the typed Go in internal/db/sqlcgen from these annotated queries against the
	// goose migration schema (see sqlc.yaml). Regenerate with: go tool sqlc generate.
	//
	// Every read and write is scoped by tenant_id so one tenant can never observe
	// another's rows: multi-tenancy is enforced in the WHERE clause, not only at the
	// transport edge.
	CreateWidget(ctx context.Context, arg CreateWidgetParams) error
	GetIdempotency(ctx context.Context, arg GetIdempotencyParams) (GetIdempotencyRow, error)
	GetWidget(ctx context.Context, arg GetWidgetParams) (Widget, error)
	// Idempotency-Key store (recipes/add-idempotent-write.md). Keyed by
	// (tenant_id, route, idempotency_key) so a client key is scoped per tenant and
	// endpoint. A row is reserved (response_status NULL) on first use and updated
	// with the response when the write completes, so a duplicate replays it. The
	// TTL is enforced with expires_at.
	// Reserve the key on first use; if a row already exists it is reclaimed ONLY
	// when expired (expires_at <= now). The affected-row count tells the caller
	// whether it won the lease (1) or a live row already exists (0); on 0 the caller
	// reads the existing row to decide replay vs. in-flight vs. mismatch. This is the
	// atomic compare-and-set that closes the concurrent-duplicate race.
	InsertIdempotency(ctx context.Context, arg InsertIdempotencyParams) (int64, error)
	// Keyset pagination over the stable (created_at, id) order WITHIN a tenant. The
	// tenant_id predicate scopes every page; when @from_start is true the
	// row-comparison guard is bypassed and the scan starts at the tenant's first
	// row; otherwise it resumes strictly after the cursor (@cursor_created_at,
	// @cursor_id) using a tuple comparison so id breaks created_at ties and pages
	// neither overlap nor skip rows. The caller asks for one more than the page size
	// to detect whether another page exists.
	ListWidgets(ctx context.Context, arg ListWidgetsParams) ([]Widget, error)
	ReleaseIdempotency(ctx context.Context, arg ReleaseIdempotencyParams) error
}

var _ Querier = (*Queries)(nil)
