// widget.v1 is the versioned wire contract for the widgets service. The package
// and directory stay versioned even at v1, per golang/services/grpc-services.md.
// Messages are transport DTOs, not database tables; domain logic lives in
// internal/core, never in generated types.

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             (unknown)
// source: widget/v1/widget.proto

package widgetv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	WidgetService_CreateWidget_FullMethodName = "/widget.v1.WidgetService/CreateWidget"
	WidgetService_GetWidget_FullMethodName    = "/widget.v1.WidgetService/GetWidget"
	WidgetService_ListWidgets_FullMethodName  = "/widget.v1.WidgetService/ListWidgets"
)

// WidgetServiceClient is the client API for WidgetService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// WidgetService manages widgets within the caller's tenant. The tenant is
// resolved from the authenticated principal on the server, never carried in a
// request field, so a caller cannot address another tenant's data.
type WidgetServiceClient interface {
	// CreateWidget creates a widget. Returns AlreadyExists if the id is taken and
	// InvalidArgument on validation failure.
	CreateWidget(ctx context.Context, in *CreateWidgetRequest, opts ...grpc.CallOption) (*CreateWidgetResponse, error)
	// GetWidget returns a widget by id, or NotFound.
	GetWidget(ctx context.Context, in *GetWidgetRequest, opts ...grpc.CallOption) (*GetWidgetResponse, error)
	// ListWidgets returns a keyset-paginated page of widgets.
	ListWidgets(ctx context.Context, in *ListWidgetsRequest, opts ...grpc.CallOption) (*ListWidgetsResponse, error)
}

type widgetServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewWidgetServiceClient(cc grpc.ClientConnInterface) WidgetServiceClient {
	return &widgetServiceClient{cc}
}

func (c *widgetServiceClient) CreateWidget(ctx context.Context, in *CreateWidgetRequest, opts ...grpc.CallOption) (*CreateWidgetResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateWidgetResponse)
	err := c.cc.Invoke(ctx, WidgetService_CreateWidget_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *widgetServiceClient) GetWidget(ctx context.Context, in *GetWidgetRequest, opts ...grpc.CallOption) (*GetWidgetResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetWidgetResponse)
	err := c.cc.Invoke(ctx, WidgetService_GetWidget_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *widgetServiceClient) ListWidgets(ctx context.Context, in *ListWidgetsRequest, opts ...grpc.CallOption) (*ListWidgetsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListWidgetsResponse)
	err := c.cc.Invoke(ctx, WidgetService_ListWidgets_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// WidgetServiceServer is the server API for WidgetService service.
// All implementations must embed UnimplementedWidgetServiceServer
// for forward compatibility.
//
// WidgetService manages widgets within the caller's tenant. The tenant is
// resolved from the authenticated principal on the server, never carried in a
// request field, so a caller cannot address another tenant's data.
type WidgetServiceServer interface {
	// CreateWidget creates a widget. Returns AlreadyExists if the id is taken and
	// InvalidArgument on validation failure.
	CreateWidget(context.Context, *CreateWidgetRequest) (*CreateWidgetResponse, error)
	// GetWidget returns a widget by id, or NotFound.
	GetWidget(context.Context, *GetWidgetRequest) (*GetWidgetResponse, error)
	// ListWidgets returns a keyset-paginated page of widgets.
	ListWidgets(context.Context, *ListWidgetsRequest) (*ListWidgetsResponse, error)
	mustEmbedUnimplementedWidgetServiceServer()
}

// UnimplementedWidgetServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedWidgetServiceServer struct{}

func (UnimplementedWidgetServiceServer) CreateWidget(context.Context, *CreateWidgetRequest) (*CreateWidgetResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateWidget not implemented")
}
func (UnimplementedWidgetServiceServer) GetWidget(context.Context, *GetWidgetRequest) (*GetWidgetResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetWidget not implemented")
}
func (UnimplementedWidgetServiceServer) ListWidgets(context.Context, *ListWidgetsRequest) (*ListWidgetsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListWidgets not implemented")
}
func (UnimplementedWidgetServiceServer) mustEmbedUnimplementedWidgetServiceServer() {}
func (UnimplementedWidgetServiceServer) testEmbeddedByValue()                       {}

// UnsafeWidgetServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to WidgetServiceServer will
// result in compilation errors.
type UnsafeWidgetServiceServer interface {
	mustEmbedUnimplementedWidgetServiceServer()
}

func RegisterWidgetServiceServer(s grpc.ServiceRegistrar, srv WidgetServiceServer) {
	// If the following call panics, it indicates UnimplementedWidgetServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&WidgetService_ServiceDesc, srv)
}

func _WidgetService_CreateWidget_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateWidgetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WidgetServiceServer).CreateWidget(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WidgetService_CreateWidget_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WidgetServiceServer).CreateWidget(ctx, req.(*CreateWidgetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WidgetService_GetWidget_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetWidgetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WidgetServiceServer).GetWidget(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WidgetService_GetWidget_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WidgetServiceServer).GetWidget(ctx, req.(*GetWidgetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WidgetService_ListWidgets_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListWidgetsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WidgetServiceServer).ListWidgets(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WidgetService_ListWidgets_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WidgetServiceServer).ListWidgets(ctx, req.(*ListWidgetsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// WidgetService_ServiceDesc is the grpc.ServiceDesc for WidgetService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var WidgetService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "widget.v1.WidgetService",
	HandlerType: (*WidgetServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateWidget",
			Handler:    _WidgetService_CreateWidget_Handler,
		},
		{
			MethodName: "GetWidget",
			Handler:    _WidgetService_GetWidget_Handler,
		},
		{
			MethodName: "ListWidgets",
			Handler:    _WidgetService_ListWidgets_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "widget/v1/widget.proto",
}
