// widget.v1 is the versioned wire contract for the widgets service. The package
// and directory stay versioned even at v1, per golang/services/grpc-services.md.
// Messages are transport DTOs, not database tables; domain logic lives in
// internal/core, never in generated types.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: widget/v1/widget.proto

package widgetv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Widget is the wire representation of a widget.
type Widget struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Widget) Reset() {
	*x = Widget{}
	mi := &file_widget_v1_widget_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Widget) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Widget) ProtoMessage() {}

func (x *Widget) ProtoReflect() protoreflect.Message {
	mi := &file_widget_v1_widget_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Widget.ProtoReflect.Descriptor instead.
func (*Widget) Descriptor() ([]byte, []int) {
	return file_widget_v1_widget_proto_rawDescGZIP(), []int{0}
}

func (x *Widget) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Widget) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Widget) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

type CreateWidgetRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateWidgetRequest) Reset() {
	*x = CreateWidgetRequest{}
	mi := &file_widget_v1_widget_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateWidgetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateWidgetRequest) ProtoMessage() {}

func (x *CreateWidgetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_widget_v1_widget_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateWidgetRequest.ProtoReflect.Descriptor instead.
func (*CreateWidgetRequest) Descriptor() ([]byte, []int) {
	return file_widget_v1_widget_proto_rawDescGZIP(), []int{1}
}

func (x *CreateWidgetRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *CreateWidgetRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type CreateWidgetResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Widget        *Widget                `protobuf:"bytes,1,opt,name=widget,proto3" json:"widget,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateWidgetResponse) Reset() {
	*x = CreateWidgetResponse{}
	mi := &file_widget_v1_widget_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateWidgetResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateWidgetResponse) ProtoMessage() {}

func (x *CreateWidgetResponse) ProtoReflect() protoreflect.Message {
	mi := &file_widget_v1_widget_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateWidgetResponse.ProtoReflect.Descriptor instead.
func (*CreateWidgetResponse) Descriptor() ([]byte, []int) {
	return file_widget_v1_widget_proto_rawDescGZIP(), []int{2}
}

func (x *CreateWidgetResponse) GetWidget() *Widget {
	if x != nil {
		return x.Widget
	}
	return nil
}

type GetWidgetRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetWidgetRequest) Reset() {
	*x = GetWidgetRequest{}
	mi := &file_widget_v1_widget_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetWidgetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetWidgetRequest) ProtoMessage() {}

func (x *GetWidgetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_widget_v1_widget_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetWidgetRequest.ProtoReflect.Descriptor instead.
func (*GetWidgetRequest) Descriptor() ([]byte, []int) {
	return file_widget_v1_widget_proto_rawDescGZIP(), []int{3}
}

func (x *GetWidgetRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type GetWidgetResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Widget        *Widget                `protobuf:"bytes,1,opt,name=widget,proto3" json:"widget,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetWidgetResponse) Reset() {
	*x = GetWidgetResponse{}
	mi := &file_widget_v1_widget_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetWidgetResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetWidgetResponse) ProtoMessage() {}

func (x *GetWidgetResponse) ProtoReflect() protoreflect.Message {
	mi := &file_widget_v1_widget_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetWidgetResponse.ProtoReflect.Descriptor instead.
func (*GetWidgetResponse) Descriptor() ([]byte, []int) {
	return file_widget_v1_widget_proto_rawDescGZIP(), []int{4}
}

func (x *GetWidgetResponse) GetWidget() *Widget {
	if x != nil {
		return x.Widget
	}
	return nil
}

type ListWidgetsRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// page_size is the maximum number of widgets to return. The server clamps it
	// to a default when unset (0) and to a maximum when too large.
	PageSize int32 `protobuf:"varint,1,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	// page_token is the opaque cursor returned as next_page_token by a prior call.
	// Empty starts from the beginning. A malformed token is InvalidArgument.
	PageToken     string `protobuf:"bytes,2,opt,name=page_token,json=pageToken,proto3" json:"page_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListWidgetsRequest) Reset() {
	*x = ListWidgetsRequest{}
	mi := &file_widget_v1_widget_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListWidgetsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListWidgetsRequest) ProtoMessage() {}

func (x *ListWidgetsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_widget_v1_widget_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListWidgetsRequest.ProtoReflect.Descriptor instead.
func (*ListWidgetsRequest) Descriptor() ([]byte, []int) {
	return file_widget_v1_widget_proto_rawDescGZIP(), []int{5}
}

func (x *ListWidgetsRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *ListWidgetsRequest) GetPageToken() string {
	if x != nil {
		return x.PageToken
	}
	return ""
}

type ListWidgetsResponse struct {
	state   protoimpl.MessageState `protogen:"open.v1"`
	Widgets []*Widget              `protobuf:"bytes,1,rep,name=widgets,proto3" json:"widgets,omitempty"`
	// next_page_token is the cursor for the next page, or empty on the last page.
	NextPageToken string `protobuf:"bytes,2,opt,name=next_page_token,json=nextPageToken,proto3" json:"next_page_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListWidgetsResponse) Reset() {
	*x = ListWidgetsResponse{}
	mi := &file_widget_v1_widget_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListWidgetsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListWidgetsResponse) ProtoMessage() {}

func (x *ListWidgetsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_widget_v1_widget_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListWidgetsResponse.ProtoReflect.Descriptor instead.
func (*ListWidgetsResponse) Descriptor() ([]byte, []int) {
	return file_widget_v1_widget_proto_rawDescGZIP(), []int{6}
}

func (x *ListWidgetsResponse) GetWidgets() []*Widget {
	if x != nil {
		return x.Widgets
	}
	return nil
}

func (x *ListWidgetsResponse) GetNextPageToken() string {
	if x != nil {
		return x.NextPageToken
	}
	return ""
}

var File_widget_v1_widget_proto protoreflect.FileDescriptor

const file_widget_v1_widget_proto_rawDesc = "" +
	"\n" +
	"\x16widget/v1/widget.proto\x12\twidget.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"g\n" +
	"\x06Widget\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x129\n" +
	"\n" +
	"created_at\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\"9\n" +
	"\x13CreateWidgetRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\"A\n" +
	"\x14CreateWidgetResponse\x12)\n" +
	"\x06widget\x18\x01 \x01(\v2\x11.widget.v1.WidgetR\x06widget\"\"\n" +
	"\x10GetWidgetRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\">\n" +
	"\x11GetWidgetResponse\x12)\n" +
	"\x06widget\x18\x01 \x01(\v2\x11.widget.v1.WidgetR\x06widget\"P\n" +
	"\x12ListWidgetsRequest\x12\x1b\n" +
	"\tpage_size\x18\x01 \x01(\x05R\bpageSize\x12\x1d\n" +
	"\n" +
	"page_token\x18\x02 \x01(\tR\tpageToken\"j\n" +
	"\x13ListWidgetsResponse\x12+\n" +
	"\awidgets\x18\x01 \x03(\v2\x11.widget.v1.WidgetR\awidgets\x12&\n" +
	"\x0fnext_page_token\x18\x02 \x01(\tR\rnextPageToken2\xf6\x01\n" +
	"\rWidgetService\x12O\n" +
	"\fCreateWidget\x12\x1e.widget.v1.CreateWidgetRequest\x1a\x1f.widget.v1.CreateWidgetResponse\x12F\n" +
	"\tGetWidget\x12\x1b.widget.v1.GetWidgetRequest\x1a\x1c.widget.v1.GetWidgetResponse\x12L\n" +
	"\vListWidgets\x12\x1d.widget.v1.ListWidgetsRequest\x1a\x1e.widget.v1.ListWidgetsResponseB\x98\x01\n" +
	"\rcom.widget.v1B\vWidgetProtoP\x01Z5github.com/example/examplegrpc/api/widget/v1;widgetv1\xa2\x02\x03WXX\xaa\x02\tWidget.V1\xca\x02\tWidget\\V1\xe2\x02\x15Widget\\V1\\GPBMetadata\xea\x02\n" +
	"Widget::V1b\x06proto3"

var (
	file_widget_v1_widget_proto_rawDescOnce sync.Once
	file_widget_v1_widget_proto_rawDescData []byte
)

func file_widget_v1_widget_proto_rawDescGZIP() []byte {
	file_widget_v1_widget_proto_rawDescOnce.Do(func() {
		file_widget_v1_widget_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_widget_v1_widget_proto_rawDesc), len(file_widget_v1_widget_proto_rawDesc)))
	})
	return file_widget_v1_widget_proto_rawDescData
}

var file_widget_v1_widget_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_widget_v1_widget_proto_goTypes = []any{
	(*Widget)(nil),                // 0: widget.v1.Widget
	(*CreateWidgetRequest)(nil),   // 1: widget.v1.CreateWidgetRequest
	(*CreateWidgetResponse)(nil),  // 2: widget.v1.CreateWidgetResponse
	(*GetWidgetRequest)(nil),      // 3: widget.v1.GetWidgetRequest
	(*GetWidgetResponse)(nil),     // 4: widget.v1.GetWidgetResponse
	(*ListWidgetsRequest)(nil),    // 5: widget.v1.ListWidgetsRequest
	(*ListWidgetsResponse)(nil),   // 6: widget.v1.ListWidgetsResponse
	(*timestamppb.Timestamp)(nil), // 7: google.protobuf.Timestamp
}
var file_widget_v1_widget_proto_depIdxs = []int32{
	7, // 0: widget.v1.Widget.created_at:type_name -> google.protobuf.Timestamp
	0, // 1: widget.v1.CreateWidgetResponse.widget:type_name -> widget.v1.Widget
	0, // 2: widget.v1.GetWidgetResponse.widget:type_name -> widget.v1.Widget
	0, // 3: widget.v1.ListWidgetsResponse.widgets:type_name -> widget.v1.Widget
	1, // 4: widget.v1.WidgetService.CreateWidget:input_type -> widget.v1.CreateWidgetRequest
	3, // 5: widget.v1.WidgetService.GetWidget:input_type -> widget.v1.GetWidgetRequest
	5, // 6: widget.v1.WidgetService.ListWidgets:input_type -> widget.v1.ListWidgetsRequest
	2, // 7: widget.v1.WidgetService.CreateWidget:output_type -> widget.v1.CreateWidgetResponse
	4, // 8: widget.v1.WidgetService.GetWidget:output_type -> widget.v1.GetWidgetResponse
	6, // 9: widget.v1.WidgetService.ListWidgets:output_type -> widget.v1.ListWidgetsResponse
	7, // [7:10] is the sub-list for method output_type
	4, // [4:7] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_widget_v1_widget_proto_init() }
func file_widget_v1_widget_proto_init() {
	if File_widget_v1_widget_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_widget_v1_widget_proto_rawDesc), len(file_widget_v1_widget_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_widget_v1_widget_proto_goTypes,
		DependencyIndexes: file_widget_v1_widget_proto_depIdxs,
		MessageInfos:      file_widget_v1_widget_proto_msgTypes,
	}.Build()
	File_widget_v1_widget_proto = out.File
	file_widget_v1_widget_proto_goTypes = nil
	file_widget_v1_widget_proto_depIdxs = nil
}
